apiVersion: v2
type: application
version: 1.1.0
appVersion: 1.1.0
name: pagopa-ecommerce-payment-methods-handler
description: Microservice that handles payment methods, session and fees
dependencies:
  - name: microservice-chart
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    version: 7.5.0
